### ISSUE TITLE
Improve test suite with matrices

### ISSUE THREAD

**Issue by trentonyo** [Start-Out/todo-or-not#379]
Use matrices to test multiple versions of python, and multiple operating systems

# [Reference:](https://github.com/Start-Out/golden-paths/blob/1e14e027421398c63ee467d8fa124964ac925b97/.github/workflows/test-suite.yaml#L30)

```yaml
## ... ##
jobs:
  test_suite:
    name: Run test suite steps
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
## ... ##
```
